### ISSUE TITLE
Drop PO dir from package

### ISSUE THREAD

**Issue by burner1024** [ALIENQuake/CreateIEModZipPackage#3]
[PO dir](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/tree/master/tnt/tra/po) is unnecessary in the final package.
Its location is `$tra_dir/po`, where `tra_dir` is from `translation` stanza in [.bgforge.yml](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/.bgforge.yml). (If not specified, defaults to root dir).
Doesn't matter much, just for cleanliness.

**Comment by ALIENQuake** [comment]
I've completely missed this. It can be handled by a general rule of excluding .pot and .po but I don't think that .csv files can be excluded.

**Comment by ALIENQuake** [comment]
This cannot be implemented because it makes iemod package content different from than repository content and during the first update the local extracted mod directory will be mirrored to the content of the GitHub repository.
